production:
  site_domain:                      yoursite.com
  admin_email:                      admin@yoursite.com
  system_send_email_address:        noreply@yoursite.com
  flag_threshold:                   3
  new_comment_subject:              Yoursite.com - New comment
  failed_comment_creation_subject:  Yoursite.com - Failed comment creation
  comment_reply_subject:            Yoursite.com - {name} has replied to your comment
  
  enable_notifications: true
  enable_comment_creation_failure_notifications: true

development:
  site_domain:                      yoursite.com
  admin_email:                      info@whyiamangry.com
  system_send_email_address:        noreply@yoursite.com
  flag_threshold:                   3
  new_comment_subject:              Yoursite.com - New comment
  failed_comment_creation_subject:  Yoursite.com - Failed comment creation
  comment_reply_subject:            Yoursite.com - {name} has replied to your comment
  
  enable_notifications: true
  enable_comment_creation_failure_notifications: true

test:
  site_domain:                      yoursite.com
  admin_email:                      tests@example.com
  system_send_email_address:        sendtest@example.com
  flag_threshold:                   3
  new_comment_subject:              Yoursite.com - New comment
  failed_comment_creation_subject:  Yoursite.com - Failed comment creation
  comment_reply_subject:            Yoursite.com - {name} has replied to your comment
  
  enable_notifications: true
  enable_comment_creation_failure_notifications: true